#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class CloudScriptTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct CloudScriptTestsState> m_state;

private:
    // Autogenerated tests
    void TestClientExecuteCloudScript(TestContext& testContext);
#if HC_PLATFORM == HC_PLATFORM_WIN32 || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerExecuteCloudScript(TestContext& testContext);
#endif
    void TestExecuteEntityCloudScript(TestContext& testContext);
    void TestExecuteFunction(TestContext& testContext);
#if 0
    void TestListEventHubFunctions(TestContext& testContext);
#endif
#if 0
    void TestRegisterEventHubFunction(TestContext& testContext);
#endif

};

} // namespace Test
} // namespace PlayFab
