#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class DataTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct DataTestsState> m_state;

private:
    // Autogenerated tests
    void TestAbortFileUploads(TestContext& testContext);
    void TestDeleteFiles(TestContext& testContext);
    void TestFinalizeFileUploads(TestContext& testContext);
    void TestGetFiles(TestContext& testContext);
    void TestGetObjects(TestContext& testContext);
    void TestInitiateFileUploads(TestContext& testContext);
    void TestSetObjects(TestContext& testContext);

};

} // namespace Test
} // namespace PlayFab
