#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class InventoryTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct InventoryTestsState> m_state;

private:
    // Autogenerated tests
    void TestAddInventoryItems(TestContext& testContext);
    void TestDeleteInventoryCollection(TestContext& testContext);
    void TestDeleteInventoryItems(TestContext& testContext);
    void TestExecuteInventoryOperations(TestContext& testContext);
    void TestGetInventoryCollectionIds(TestContext& testContext);
    void TestGetInventoryItems(TestContext& testContext);
#if HC_PLATFORM == HC_PLATFORM_WIN32 || HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX
    void TestGetMicrosoftStoreAccessTokens(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32 || HC_PLATFORM == HC_PLATFORM_LINUX
    void TestGetTransactionHistory(TestContext& testContext);
#endif
    void TestPurchaseInventoryItems(TestContext& testContext);
#if 0
    void TestRedeemAppleAppStoreInventoryItems(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_ANDROID
    void TestRedeemGooglePlayInventoryItems(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32 || HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX
    void TestRedeemMicrosoftStoreInventoryItems(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32 || HC_PLATFORM == HC_PLATFORM_NINTENDO_SWITCH || HC_PLATFORM == HC_PLATFORM_LINUX
    void TestRedeemNintendoEShopInventoryItems(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32 || HC_PLATFORM == HC_PLATFORM_SONY_PLAYSTATION_4 || HC_PLATFORM == HC_PLATFORM_SONY_PLAYSTATION_5 || HC_PLATFORM == HC_PLATFORM_LINUX
    void TestRedeemPlayStationStoreInventoryItems(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32 || HC_PLATFORM == HC_PLATFORM_LINUX
    void TestRedeemSteamInventoryItems(TestContext& testContext);
#endif
    void TestSubtractInventoryItems(TestContext& testContext);
    void TestTransferInventoryItems(TestContext& testContext);
    void TestUpdateInventoryItems(TestContext& testContext);

};

} // namespace Test
} // namespace PlayFab
