#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class MultiplayerServerTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct MultiplayerServerTestsState> m_state;

private:
    // Autogenerated tests
    void TestListBuildAliases(TestContext& testContext);
    void TestListBuildSummariesV2(TestContext& testContext);
    void TestListQosServersForTitle(TestContext& testContext);
    void TestRequestMultiplayerServer(TestContext& testContext);
#if 0
    void TestRequestPartyService(TestContext& testContext);
#endif

};

} // namespace Test
} // namespace PlayFab
