#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class PlayStreamTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct PlayStreamTestsState> m_state;

private:
    // Autogenerated tests
#if 0
    void TestServerExportPlayersInSegment(TestContext& testContext);
#endif
#if 0
    void TestServerGetSegmentExport(TestContext& testContext);
#endif
#if 0
    void TestServerGetSegmentPlayerCount(TestContext& testContext);
#endif

};

} // namespace Test
} // namespace PlayFab
