#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class PlayerDataManagementTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct PlayerDataManagementTestsState> m_state;

private:
    // Autogenerated tests
    void TestClientDeletePlayerCustomProperties(TestContext& testContext);
    void TestClientGetPlayerCustomProperty(TestContext& testContext);
    void TestClientGetUserData(TestContext& testContext);
    void TestClientGetUserPublisherData(TestContext& testContext);
    void TestClientGetUserPublisherReadOnlyData(TestContext& testContext);
    void TestClientGetUserReadOnlyData(TestContext& testContext);
    void TestClientListPlayerCustomProperties(TestContext& testContext);
    void TestClientUpdatePlayerCustomProperties(TestContext& testContext);
    void TestClientUpdateUserData(TestContext& testContext);
    void TestClientUpdateUserPublisherData(TestContext& testContext);
#if HC_PLATFORM == HC_PLATFORM_GDK
    void TestServerDeletePlayerCustomProperties(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK
    void TestServerGetPlayerCustomProperty(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerGetUserData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerGetUserInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerGetUserPublisherData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerGetUserPublisherInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerGetUserPublisherReadOnlyData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerGetUserReadOnlyData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK
    void TestServerListPlayerCustomProperties(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK
    void TestServerUpdatePlayerCustomProperties(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerUpdateUserData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerUpdateUserInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerUpdateUserPublisherData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerUpdateUserPublisherInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerUpdateUserPublisherReadOnlyData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_GDK || HC_PLATFORM == HC_PLATFORM_LINUX || HC_PLATFORM == HC_PLATFORM_MAC
    void TestServerUpdateUserReadOnlyData(TestContext& testContext);
#endif

};

} // namespace Test
} // namespace PlayFab
