#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class PlayerDataManagementTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct PlayerDataManagementTestsState> m_state;

private:
    // Autogenerated tests
    void TestClientGetUserData(TestContext& testContext);
    void TestClientGetUserPublisherData(TestContext& testContext);
    void TestClientGetUserPublisherReadOnlyData(TestContext& testContext);
    void TestClientGetUserReadOnlyData(TestContext& testContext);
    void TestClientUpdateUserData(TestContext& testContext);
    void TestClientUpdateUserPublisherData(TestContext& testContext);
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerGetUserData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerGetUserInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerGetUserPublisherData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerGetUserPublisherInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerGetUserPublisherReadOnlyData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerGetUserReadOnlyData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerUpdateUserData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerUpdateUserInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerUpdateUserPublisherData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerUpdateUserPublisherInternalData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerUpdateUserPublisherReadOnlyData(TestContext& testContext);
#endif
#if HC_PLATFORM == HC_PLATFORM_WIN32
    void TestServerUpdateUserReadOnlyData(TestContext& testContext);
#endif

};

} // namespace Test
} // namespace PlayFab
