#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class ProfilesTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct ProfilesTestsState> m_state;

private:
    // Autogenerated tests
    void TestGetProfile(TestContext& testContext);
    void TestGetProfiles(TestContext& testContext);
    void TestGetTitlePlayersFromMasterPlayerAccountIds(TestContext& testContext);
    void TestSetProfileLanguage(TestContext& testContext);
    void TestSetProfilePolicy(TestContext& testContext);

};

} // namespace Test
} // namespace PlayFab
