#pragma once

#include "ServicesTestClass.h"

namespace PlayFab
{
namespace Test
{

class SegmentsTests : public ServicesTestClass
{
public:
    using ServicesTestClass::ServicesTestClass;

private:
    void AddTests() override;

    AsyncOp<void> Initialize() override;
    AsyncOp<void> Uninitialize() override;

    SharedPtr<struct SegmentsTestsState> m_state;

private:
    // Autogenerated tests
    void TestClientGetPlayerSegments(TestContext& testContext);
    void TestClientGetPlayerTags(TestContext& testContext);
#if 0
    void TestServerAddPlayerTag(TestContext& testContext);
#endif
#if 0
    void TestServerGetAllSegments(TestContext& testContext);
#endif
#if 0
    void TestServerGetPlayerSegments(TestContext& testContext);
#endif
#if 0
    void TestServerGetPlayersInSegment(TestContext& testContext);
#endif
#if 0
    void TestServerGetPlayerTags(TestContext& testContext);
#endif
#if 0
    void TestServerRemovePlayerTag(TestContext& testContext);
#endif

};

} // namespace Test
} // namespace PlayFab
